---
title: "DATA 599 Survival Analysis - Kaplan Meier Curves & Censoring"
author: ""
date: "January 19, 2023"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "./data")

library(tidyverse)
library(lubridate)
library(skimr)
library(survival)
library(survminer)
library(reReg)
library(KMsurv)
library(Ecdat)

ds=read_csv("./data/aquaticToxic.csv")

```

## KM Survival Curves for Pesticides 

#Pesticide = azoxystrobin
```{r}
at1 = ds %>% 
  filter(pesticide == "azoxystrobin")
```

```{r}
at1sf = survfit(Surv(at1$TTKD, at1$status)~at1$temp) 
ggsurvplot(fit = at1sf, data = at1, legend = "bottom", risk.table = F, conf.int=F,linetype = "strata", surv.median.line="hv") +
  labs(Title = "Survival Rate with Pesticide azoxystrobin", 
       x = "Time in Hours")

survdiff(Surv(at1$TTKD, at1$status)~at1$temp)
```
#Pesticide = carbaryl
```{r}
at2 = ds %>%
  filter(pesticide == "carbaryl")

at2sf = survfit(Surv(at2$TTKD, at2$status)~at2$temp) 
ggsurvplot(fit = at2sf, data = at2, legend = "bottom", risk.table = F, conf.int=F,linetype = "strata", surv.median.line="hv") +
  labs(Title = "Survival Rate with carbaryl", 
       x = "Time in Hours")

survdiff(Surv(at2$TTKD, at2$status)~at2$temp)
```

#Pesticide = atrazine
```{r}
at3 = ds %>%
  filter(pesticide == "atrazine")

at3sf = survfit(Surv(at3$TTKD, at3$status)~at3$temp) 
ggsurvplot(fit = at3sf, data = at3, legend = "bottom", risk.table = F, conf.int=F,linetype = "strata", surv.median.line="hv") +
  labs(Title = "Survival Rate with atrazine", 
       x = "Time in Hours")

survdiff(Surv(at3$TTKD, at3$status)~at3$temp)
```
##Temperature Analysis
#Temp = 18
```{r}
temp18 = ds %>%
  filter(temp == 18)

ggsurvplot(fit= survfit(Surv(temp18$TTKD, temp18$status)~temp18$pesticide), data = temp18, surv.median.line="hv") +
  labs(Title = "Survival Plot Temperature is 18", 
       x = "Time in Hours")

survdiff(Surv(temp18$TTKD, temp18$status)~temp18$pesticide)
```
#Temp = 24
```{r}
temp24 = ds %>%
  filter(temp == 24)

ggsurvplot(fit= survfit(Surv(temp24$TTKD, temp24$status)~temp24$pesticide), data = temp24, surv.median.line="hv") +
  labs(Title = "Survival Plot Temperature is 24", 
       x = "Time in Hours")

survdiff(Surv(temp24$TTKD, temp24$status)~temp24$pesticide)
```

#Temp = 30 
```{r}
temp30 = ds %>%
  filter(temp == 30)

ggsurvplot(fit= survfit(Surv(temp30$TTKD, temp30$status)~temp30$pesticide), data = temp30, surv.median.line="hv") +
  labs(Title = "Survival Plot Temperature is 30", 
       x = "Time in Hours")

survdiff(Surv(temp30$TTKD, temp30$status)~temp30$pesticide)
```

